"""Analytical equilibrium conditions for the DPP contracting game."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from typing import Iterable, Sequence

PROJECT_ROOT = Path(__file__).resolve().parents[1]
CODE_DIR = PROJECT_ROOT / "code"
TABLE_DIR = PROJECT_ROOT / "paper" / "tables"


def load_model_module():
    spec = importlib.util.spec_from_file_location("model_setup", CODE_DIR / "02_model_setup.py")
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules["model_setup"] = module
    spec.loader.exec_module(module)
    return module


def latex_table(headers: Sequence[str], rows: Iterable[Sequence[str]], caption: str, label: str, wide: bool = False) -> str:
    column_spec = "p{0.22\\linewidth}" + "p{0.34\\linewidth}" * (len(headers) - 1)
    table_env = "table*" if wide else "table"
    lines = [
        f"\\begin{{{table_env}}}[t]",
        "\\centering",
        "\\begingroup",
        "\\setlength{\\tabcolsep}{3pt}",
        "\\small",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        f"\\begin{{tabular}}{{{column_spec}}}",
        "\\toprule",
        " & ".join(headers) + " \\\\",
        "\\midrule",
    ]
    for row in rows:
        lines.append(" & ".join(row) + " \\\\")
    lines.extend(["\\bottomrule", "\\end{tabular}", "\\endgroup", f"\\end{{{table_env}}}", ""])
    return "\n".join(lines)


def write_payoff_matrix() -> None:
    rows = [
        (
            "High-quality disclosure",
            "$V+B+g-C_H-r_H$",
            "$R-B-vp^2-kS-m\\phi^2$",
        ),
        (
            "Low-quality disclosure",
            "$V+B_L-C_L-pF-r_L$",
            "$\\beta R-L-vp^2-B_L-kS-m\\phi^2+\\eta pF$",
        ),
        (
            "Non-disclosure",
            "$O$",
            "$-L$",
        ),
    ]
    table = latex_table(
        ["Supplier strategy", "Supplier payoff", "Buyer payoff"],
        rows,
        "Payoff matrix after the buyer selects a DPP governance contract.",
        "tab:payoff_matrix",
    )
    (TABLE_DIR / "table_payoff_matrix.tex").write_text(table, encoding="utf-8")


def write_equilibrium_conditions() -> None:
    rows = [
        (
            "High-quality disclosure",
            "$pF+(B-B_L)+g \\geq (1-\\lambda)C_H+(r_H-r_L)$ and "
            "$V+B+g-C_H-r_H \\geq O$",
            "Supplier chooses high-quality DPP data when the combined incentive, reputation, and expected enforcement advantage exceeds the cost saving and risk advantage of partial disclosure, and participation beats the outside option.",
        ),
        (
            "Low-quality disclosure",
            "$pF+(B-B_L)+g < (1-\\lambda)C_H+(r_H-r_L)$ and "
            "$V+B_L-C_L-pF-r_L \\geq O$",
            "Partial disclosure is selected when shirking remains cheaper than complete disclosure after expected penalties, but staying in the buyer relationship still beats non-disclosure.",
        ),
        (
            "Non-disclosure",
            "$O>V+B+g-C_H-r_H$ and $O>V+B_L-C_L-pF-r_L$",
            "The supplier exits or refuses DPP disclosure when both disclosure strategies fall below the outside option.",
        ),
        (
            "Audit deterrence threshold",
            "$pF \\geq (C_H-C_L)+(r_H-r_L)-(B-B_L)-g$",
            "Audit and penalty clauses deter low-quality disclosure only when expected punishment covers the supplier's savings from lower-quality data net of incentives and reputation.",
        ),
        (
            "Support threshold",
            "$C_H(q,S)\\leq V+B+g-r_H-O$",
            "Capability-building support makes high-quality disclosure feasible by lowering the effective disclosure cost enough to satisfy participation.",
        ),
    ]
    table = latex_table(
        ["Equilibrium object", "Condition", "Interpretation"],
        rows,
        "Supplier equilibrium conditions in the DPP disclosure game.",
        "tab:equilibrium_conditions",
        wide=True,
    )
    (TABLE_DIR / "table_equilibrium_conditions.tex").write_text(table, encoding="utf-8")


def write_symbolic_summary() -> None:
    note = (
        "% Symbolic audit deterrence threshold generated by 03_equilibrium_analysis.py\n"
        "% pF must be at least: (1-lambda)C_H + (r_H-r_L) - (B-B_L) - g\n"
        "% Buyer high-quality payoff net of governance costs: R - B - v*p^2 - k*S - m*phi^2\n"
    )
    (TABLE_DIR / "symbolic_threshold_notes.tex").write_text(note, encoding="utf-8")


def main() -> None:
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    model = load_model_module()
    model.write_default_files()
    write_payoff_matrix()
    write_equilibrium_conditions()
    write_symbolic_summary()
    print(f"Wrote equilibrium tables to {TABLE_DIR}")


if __name__ == "__main__":
    main()
